directory: ~/beets
library: ~/.local/share/beets/beets.blb

plugins: chroma duplicates fetchart embedart

import:
    incremental: no
    move: yes

paths:
    default: $albumartist/$album%aunique{}/$track $title
    singleton: $albumartist/$album%aunique{}/$track $title
    comp: $albumartist/$album%aunique{}/$track $title

fetchart:
    sources: itunes amazon albumart google wikipedia fanarttv
